# Generated by Django 2.1.5 on 2022-12-18 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20221218_0521'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='f_name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='l_name',
            new_name='last_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='m_name',
        ),
        migrations.AddField(
            model_name='profile',
            name='middle_name',
            field=models.CharField(blank=True, help_text='Optional, but helpful.', max_length=70),
        ),
        migrations.AddField(
            model_name='profile',
            name='suffix',
            field=models.CharField(blank=True, max_length=3),
        ),
    ]
